/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectInterface;

/**
 *
 * @author macbookpro
 */
public class HistorialHabi extends javax.swing.JFrame {
    
    public static String numHabi = "";
    public static inicio ini;

    /**
     * Creates new form HistorialHabi
     */
    public HistorialHabi(inicio ini) {
        initComponents();
         this.ini = ini;
        ini.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        HabiNumber = new javax.swing.JScrollPane();
        habiNumber = new javax.swing.JTextArea();
        loadHabi = new javax.swing.JButton();
        x = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingrese Numero Habitacion:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        habiNumber.setColumns(20);
        habiNumber.setRows(5);
        HabiNumber.setViewportView(habiNumber);

        getContentPane().add(HabiNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 139, 170, 30));

        loadHabi.setText("load");
        loadHabi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadHabiActionPerformed(evt);
            }
        });
        getContentPane().add(loadHabi, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 60, -1));

        x.setText("x");
        getContentPane().add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadHabiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadHabiActionPerformed
       this.numHabi = habiNumber.getText();
    }//GEN-LAST:event_loadHabiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistorialHabi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistorialHabi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistorialHabi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistorialHabi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistorialHabi(ini).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane HabiNumber;
    private javax.swing.JTextArea habiNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loadHabi;
    private javax.swing.JButton x;
    // End of variables declaration//GEN-END:variables
}
