/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectInterface;

/**
 *
 * @author macbookpro
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registroClientes = new javax.swing.JButton();
        reservacionID = new javax.swing.JButton();
        CheckIn = new javax.swing.JButton();
        checkOut = new javax.swing.JButton();
        HistorialH = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registroClientes.setText("Registro Clientes");
        registroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroClientesActionPerformed(evt);
            }
        });
        getContentPane().add(registroClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 120, -1));

        reservacionID.setText("Busqueda Resn ID");
        reservacionID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservacionIDActionPerformed(evt);
            }
        });
        getContentPane().add(reservacionID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        CheckIn.setText("Check In");
        CheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckInActionPerformed(evt);
            }
        });
        getContentPane().add(CheckIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 120, -1));

        checkOut.setText("Check Out");
        checkOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutActionPerformed(evt);
            }
        });
        getContentPane().add(checkOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 120, -1));

        HistorialH.setText("Historial Hab");
        HistorialH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistorialHActionPerformed(evt);
            }
        });
        getContentPane().add(HistorialH, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 120, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkOutActionPerformed

    private void registroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroClientesActionPerformed
        customerR csr = new customerR(this);
    }//GEN-LAST:event_registroClientesActionPerformed

    private void reservacionIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservacionIDActionPerformed
        seekById sbi = new seekById(this);
    }//GEN-LAST:event_reservacionIDActionPerformed

    private void CheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckInActionPerformed
        checkIn chn = new checkIn(this);
    }//GEN-LAST:event_CheckInActionPerformed

    private void HistorialHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistorialHActionPerformed
        HistorialHabi hhn = new HistorialHabi(this);
    }//GEN-LAST:event_HistorialHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckIn;
    private javax.swing.JButton HistorialH;
    private javax.swing.JButton checkOut;
    private javax.swing.JButton registroClientes;
    private javax.swing.JButton reservacionID;
    // End of variables declaration//GEN-END:variables
}
