/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectInterface;

import ProjectTools.*;
import ProjectClasses.*;
import javax.swing.JOptionPane;

/**
 *
 * @author macbookpro
 */
public class SeekById extends javax.swing.JFrame {
    
    public static String id = "";

    public static inicio ini;
    /**
     * Creates new form seekById
     */
    public SeekById(inicio ini) {
        initComponents();
        
        this.ini = ini;
        ini.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        x = new javax.swing.JButton();
        loadID = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        x.setText("x");
        x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xActionPerformed(evt);
            }
        });
        jPanel2.add(x, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 22, 40, -1));

        loadID.setText("load");
        loadID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadIDActionPerformed(evt);
            }
        });
        jPanel2.add(loadID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 60, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xActionPerformed
        this.dispose();
        inicio ini = new inicio();
        ini.setVisible(true);
    }//GEN-LAST:event_xActionPerformed

    private void loadIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadIDActionPerformed
       String ci = JOptionPane.showInputDialog(null,"Ingrese la cedula de identidad: ", "1234567"); 
       while (!Checker.isNum(ci) & Integer.parseInt(ci)>0 & Integer.parseInt(ci)<=999999999) {
           ci = JOptionPane.showInputDialog(null,"Ingrese una cedula valida: ", "1234567"); 
       }
       String data1 = CSVreader.getCsv("Booking_hotel - General.csv");
       SimpleList myList = Parser.parseReservation(data1);
       NodoLista aux = myList.getHead();
       while (aux != null){
           Reservation reserva = (Reservation) aux.getData();
           if(reserva.getCi().equalsIgnoreCase(ci)){
                String data = Parser.reverseParseReservation(reserva);
                JOptionPane.showMessageDialog(rootPane, data, "Reserva de " + ci, HEIGHT);   
                System.out.println("Proceso exitoso!");
                this.dispose();
                inicio ini = new inicio();
                ini.setVisible(true);
           }
           aux = aux.getPnext();
       }
       System.out.println("Proceso fallido :(!");
       this.dispose();
       inicio ini = new inicio();
       ini.setVisible(true);
       
    }//GEN-LAST:event_loadIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeekById.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeekById.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeekById.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeekById.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeekById(ini).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loadID;
    private javax.swing.JButton x;
    // End of variables declaration//GEN-END:variables
}
